services:
  app:
    build: .
    container_name: appointment-agent
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    env_file:
      - .env
